@PlataformaFutevolei.Api_HostAddress = http://localhost:5000

POST {{PlataformaFutevolei.Api_HostAddress}}/api/autenticacao/registrar-por-convite
Content-Type: application/json

{
  "tokenConvite": "TOKEN_DO_CONVITE",
  "nome": "Organizador Convidado",
  "email": "organizador@futevolei.com",
  "senha": "123456"
}

###

POST {{PlataformaFutevolei.Api_HostAddress}}/api/autenticacao/login
Content-Type: application/json

{
  "email": "admin@futevolei.com",
  "senha": "123456"
}

###
